FROM fedora:42@sha256:ee88ab8a5c8bf78687ddcecadf824767e845adc19d8cdedb56f48521eb162b43

ARG MESA_VERSION="24.1.2-101"

USER 0

# Install the patched mesa-krunkit drivers
RUN dnf -y install dnf-plugins-core && \
    dnf -y copr enable slp/mesa-krunkit epel-9-aarch64 && \
    dnf -y install \
        mesa-vulkan-drivers-$MESA_VERSION.el9.aarch64 && \
    dnf clean all
