ARG MESA_VERSION=23.3.5-102

FROM fedora:41@sha256:3ec60eb34fa1a095c0c34dd37cead9fd38afb62612d43892fcf1d3425c32bc1e
USER 0

# Install the patched mesa-krunkit drivers
RUN dnf -y install dnf-plugins-core && \
    dnf -y copr enable slp/mesa-krunkit && \
    dnf -y install \
        mesa-vulkan-drivers-${MESA_VERSION} \
        vulkan-loader-devel vulkan-tools vulkan-loader && \
    dnf clean all
